from maze_generators.DepthFirstMazeGenerator import DepthFirstMazeGenerator
from maze_generators.RecursiveDivisionMazeGenerator import RecursiveDivisionMazeGenerator

(DepthFirstMazeGenerator, RecursiveDivisionMazeGenerator)
